### ISSUE TITLE
プラグインロード失敗

### ISSUE THREAD

**Issue by sunchurch** [anaso/homebridge-nature-remo-cloud-ir#2]
プラグインをインストール後、起動時にロードを失敗している模様です。
解決法のご教示お願いしたいです...
Homebridge v1.2.4
```
[14/12/2020, 01:52:20] [Config] Initializing config platform...
[14/12/2020, 01:52:20] [Config] Running in Service Mode
[14/12/2020, 01:52:20] Error loading platform requested in your config.json at position 2
[14/12/2020, 01:52:20] Error: The requested platform 'AnasoNatureRemoCloudIR' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:385:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:151:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
```

**Comment by anaso** [comment]
申し訳ありません！
TypeScriptから変換した後のJavaScriptが本来必要だと思うのですが一切入っていませんでした。

変換後のdistフォルダを追加したので再度ダウンロードしていただき、
npmのグローバルインストール先に配置することで使えるようになる... と思います。

私の環境
- npm v6.14.8
- Raspbian GNU/Linux 10 (buster)

では
`/usr/local/lib/node_modules/`
でした。
最終的には
`/usr/local/lib/node_modules/@anaso/homebridge-nature-remo-cloud-ir/dist`
のようになると思います。
一度これで試してもらえますか？

**Comment by sunchurch** [comment]
検証するのが遅くなって申し訳ないです。
配置後プラグインが使えるようになりました。
ありがとうございます！
